name: Temp

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Set tag var
         id: vars
         run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
       - name: Show var
         run: |
           echo ${{ steps.vars.outputs.docker_tag }}
